server:
  port: 6666

spring:
  cloud:
    config:
      enabled: false
      fail-fast: true
    consul:
      port: 8500
      host: 127.0.0.1
      discovery:
        heartbeat:
          enabled: true
          ttlValue: 5
        preferIpAddress: true
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        query-passing: true
        enabled: true
        register: true